### ISSUE TITLE
crystal/fonts

### ISSUE THREAD

**Issue by dm2912** [british-choi/EmuELEC#1]
Hey there, 

Sorry to do as issue but since github got rid of private messaging theres no easy way. Saw that you did the korean translations for Crystal theme so I have brought those edits over into my master branch.

I have also made changes in how fonts are handled. Fonts are now defined at the start of the language file, so for instance, 

![image](https://user-images.githubusercontent.com/25871666/111674444-e99bf380-8813-11eb-9fb5-f5022d2dbcad.png)

Then i have replaced all font instances throughout the theme with

![image](https://user-images.githubusercontent.com/25871666/111674530-0506fe80-8814-11eb-95fb-0999819e59bc.png)

The benefit of this is fonts can be changed systemwide by language to cover systems that use non-western fonts

It also means If you dont want to have to maintain a branch for the korean translation if you dont want to deal with merges etc.  you should be able to use my master branch now and the font should automatically change if lang is set as ko.

Cheers
Dim

**Comment by british-choi** [comment]
@dm2912 
Thanks for supporting korean language

**Comment by dm2912** [comment]
> @dm2912
> Thanks for supporting korean language

no problem. your edits actually gave me the idea to move fonts to the language files so that other non-western languages can be added more easily :D
