### ISSUE TITLE
In the game list interface of ES, my ROM becomes Korean. 

### ISSUE THREAD

**Issue by asdone7** [british-choi/EmuELEC#3]
Hello, I have encountered some problems and need your guidance.

In the game list interface of ES, my ROM becomes Korean. How can I make it displayed in other languages.Looking forward to your reply. Thank you

**Comment by british-choi** [comment]
@asdone7
Are you not Korean?
If there is no gamelists.xml in es, the game name is displayed in Korean for mame games.
Write the name tag in your language in gamelists.xml.

**Comment by british-choi** [comment]
> ```
> Hello, I have encountered some problems and need your guidance.
> ```
> 
> In the game list interface of ES, my ROM becomes Korean. How can I make it displayed in other languages.Looking forward to your reply. Thank you

Looks like you've already found the answer.
I will close the issue.

**Comment by asdone7** [comment]
@british-choi 
Sorry for the delay.

Thank you for your reply

Yes, I found the answer。
I am now troubled by the problem of "flycast" loading fonts.

Thank you again.
